"use client";

import { useEffect, useState } from "react";
import type { DemoOrder } from "../../../lib/demo-data";
import { COMPLIANCE_PERMISSIONS, hasPermission, type Role } from "../../../lib/frank";
import { EmptyState, Metric, SectionHeader, StatusBadge, displayLabel, etb, fmt, type EndOfDayControl, type ReconBatch } from "../shared/broker-foundation";

export function SettlementPage({ orders, onOpen, onExport }: { orders: DemoOrder[]; onOpen: (order: DemoOrder) => void; onExport: () => void }) {
  const queue = orders.filter((order) => ["settlement_pending", "partially_filled", "settled"].includes(order.status) || order.trades?.some((trade) => trade.settlementStatus !== "settled"));
  const settledCash = queue.filter((order) => (order.cashStatus ?? (order.status === "settled" ? "settled" : "pending")) === "settled").length;
  const settledSecurities = queue.filter((order) => (order.securitiesStatus ?? (order.status === "settled" ? "settled" : "pending")) === "settled").length;
  return <><SectionHeader eyebrow="POST-TRADE CONTROL" title="Settlement tracking" copy="Confirm cash and securities legs, value dates, and operational exceptions." action={<button className="btn secondary" onClick={onExport}>Export queue</button>} /><section className="metric-grid settlement-metrics"><Metric label="Settlement records" value={String(queue.length)} note={`${queue.filter((order) => order.status !== "settled").length} awaiting completion`} tone="warning" /><Metric label="Cash confirmed" value={`${settledCash} / ${queue.length}`} note={`${queue.length - settledCash} awaiting confirmation`} tone="success" /><Metric label="Securities confirmed" value={`${settledSecurities} / ${queue.length}`} note={`${queue.length - settledSecurities} awaiting confirmation`} tone="purple" /><Metric label="Exceptions" value={String(queue.filter((order) => order.cashStatus === "exception" || order.securitiesStatus === "exception").length)} note="From settlement records" tone="danger" /></section><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Trade / order</th><th>Client</th><th>Instrument</th><th>Value date</th><th className="num">Net amount</th><th>Cash</th><th>Securities</th><th>Overall</th></tr></thead><tbody>{queue.map((order) => { const cash = order.cashStatus ?? (order.status === "settled" ? "settled" : "pending"); const securities = order.securitiesStatus ?? (order.status === "settled" ? "settled" : "pending"); return <tr key={order.id} onClick={() => onOpen(order)}><td><b>{order.tradeId ?? "Trade pending"}</b><small>{order.id}</small></td><td><b>{order.client}</b></td><td><b>{order.symbol}</b><small>{order.side.toUpperCase()} {fmt.format(order.tradeQuantity ?? order.quantity)}</small></td><td><b>{order.settlementDate ?? "Pending"}</b></td><td className="num"><b>{fmt.format(order.tradeNet ?? order.estimatedNet)}</b><small>ETB</small></td><td><span className={`leg ${cash === "settled" ? "done" : "pending"}`}>{displayLabel(cash)}</span></td><td><span className={`leg ${securities === "settled" ? "done" : "pending"}`}>{displayLabel(securities)}</span></td><td><StatusBadge status={order.status} /></td></tr>; })}</tbody></table></div></section></>;
}

const reconciliationFeeds = [
  ["esx_executions", "ESX executions", "cash, securities or fee"],
  ["csd_positions", "CSD positions", "csd_position · account|symbol"],
  ["bank_balances", "Bank balances", "bank_balance · pooled account"],
  ["fees_settlement", "Fees & settlement", "fee or settlement_obligation"],
  ["client_money", "Client-money subledger", "client_money · pooled account"],
  ["general_ledger", "General ledger", "general_ledger · role or code"],
] as const;

export function ReconciliationPage({ batch, batches, endOfDay, busy, role, focusId, onSelectBatch, onFile, onDownload, onResolve, onSignOff, onReprocess, onBusinessDay, resolvingId }: { batch: ReconBatch; batches: ReconBatch[]; endOfDay: EndOfDayControl; busy: boolean; role: Role; focusId?: string | null; onSelectBatch: (batch: ReconBatch) => void; onFile: (file: File, feedType: string) => void; onDownload: () => void; onResolve: (id: string) => void; onSignOff: (evidenceReference: string) => void; onReprocess: (reason: string) => void; onBusinessDay: (action: "close" | "reopen", detail: string) => void; resolvingId: string | null }) {
  const [evidenceReference, setEvidenceReference] = useState("");
  const [feedType, setFeedType] = useState("esx_executions");
  const [closeEvidence, setCloseEvidence] = useState("");
  const [reopenReason, setReopenReason] = useState("");
  const [reprocessReason, setReprocessReason] = useState("");
  const openExceptions = batch.exceptions.filter((exception) => exception.status !== "resolved");
  const matchRate = batch.totalRecords ? (batch.matchedRecords / batch.totalRecords) * 100 : 0;
  const selectedFeed = reconciliationFeeds.find(([value]) => value === feedType) ?? reconciliationFeeds[0];
  useEffect(() => {
    if (!focusId) return;
    const reference = batch.exceptions.find((item) => item.id === focusId)?.reference ?? focusId;
    const row = Array.from(document.querySelectorAll<HTMLElement>(".exception-row")).find((item) => item.textContent?.includes(reference));
    row?.scrollIntoView({ block: "center" });
    row?.classList.add("focused-record");
    return () => row?.classList.remove("focused-record");
  }, [focusId, openExceptions.length, batch.exceptions]);
  return <>
    <SectionHeader eyebrow="END-OF-DAY CONTROL" title="Reconciliation" copy="Import external confirmations, and resolve cash or securities inconsistencies. Complete the controls to formally close the brokerage business day." action={<button className="btn secondary" onClick={onDownload}>Download CSV template</button>} />
    <section className={`panel eod-control ${endOfDay.status === "closed" ? "closed" : endOfDay.ready ? "ready" : "blocked"}`}>
      <div className="panel-head"><div><span className="eyebrow">BUSINESS DAY · {endOfDay.businessDate || "CURRENT"}</span><h2>{endOfDay.status === "closed" ? "Day closed" : endOfDay.ready ? "Ready for independent close" : "Close controls in progress"}</h2></div><span className={`status ${endOfDay.status === "closed" ? "status-success" : endOfDay.ready ? "status-brand" : "status-warning"}`}><i />{displayLabel(endOfDay.status)}</span></div>
      <div className="eod-checks">{endOfDay.checks.map((check) => <article className={check.passed ? "passed" : "failed"} key={check.key}><span>{check.passed ? "✓" : "!"}</span><div><b>{check.label}</b><small>{check.detail}</small></div></article>)}</div>
      {endOfDay.status === "closed" ? <div className="eod-decision"><p><b>Cut-off:</b> {endOfDay.cutoffAt ? new Date(endOfDay.cutoffAt).toLocaleString("en-GB") : "Recorded"} · {endOfDay.closedBy ?? "Authorized reviewer"}<br /><small>{endOfDay.closeEvidence}</small></p>{role === "broker_admin" && <><label>Exceptional reopening reason<input value={reopenReason} maxLength={500} onChange={(event) => setReopenReason(event.target.value)} placeholder="Explain the late event or correction requiring the day to reopen" /></label><button className="btn danger" disabled={resolvingId === "eod_reopen" || reopenReason.trim().length < 10} onClick={() => onBusinessDay("reopen", reopenReason)}>Authorize reopening</button></>}</div> : hasPermission(role, COMPLIANCE_PERMISSIONS.reconciliationSignoff) && <div className="eod-decision"><p>The cut-off is immutable after close. A different broker administrator must authorize any reopening.</p><label>Control-pack reference<input value={closeEvidence} maxLength={160} onChange={(event) => setCloseEvidence(event.target.value)} placeholder="EOD pack, bank, CSD and reviewer reference" /></label><button className="btn primary" disabled={!endOfDay.ready || resolvingId === "eod_close" || closeEvidence.trim().length < 3} onClick={() => onBusinessDay("close", closeEvidence)}>Close business day</button></div>}
    </section>
    <div className="recon-grid">
      <section className={`upload-card ${busy ? "processing" : ""}`}><span>{busy ? "···" : "⇧"}</span><h3>{busy ? "Validating and matching…" : "Upload trade confirmations and control evidence"}</h3><label className="recon-feed-label">Source feed<select value={feedType} disabled={busy || endOfDay.status === "closed"} onChange={(event) => setFeedType(event.target.value)}>{reconciliationFeeds.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><p>CSV · reference, type, actual_value<br />Expected type: {selectedFeed[2]} · up to 50,000 rows</p><label className={`btn primary ${busy || endOfDay.status === "closed" ? "disabled" : ""}`}>{busy ? "Processing safely" : endOfDay.status === "closed" ? "Business day closed" : "Choose CSV file"}<input type="file" accept=".csv,text/csv" disabled={busy || endOfDay.status === "closed"} onChange={(event) => { const file = event.target.files?.[0]; if (file) onFile(file, feedType); event.target.value = ""; }} /></label></section>
      <section className="panel recon-summary"><div className="recon-batch-picker"><span className="eyebrow">BATCH EVIDENCE</span>{batches.length > 1 && <select aria-label="Reconciliation batch" value={batch.id} onChange={(event) => { const selected = batches.find((item) => item.id === event.target.value); if (selected) onSelectBatch(selected); }}>{batches.map((item) => <option key={item.id} value={item.id}>{item.id} · {displayLabel(item.feedType ?? "legacy")}{item.status === "superseded" ? " · superseded" : ""}</option>)}</select>}</div><h2>{batch.id}</h2><small>{displayLabel(batch.feedType ?? "legacy batch")} · {batch.fileName ?? "Demonstration seed"} · attempt {batch.attemptNumber ?? 1}</small><div><span><small>Records</small><b>{batch.totalRecords}</b></span><span><small>Matched</small><b className="positive">{batch.matchedRecords}</b></span><span><small>Exceptions</small><b className={batch.exceptionRecords ? "negative" : "positive"}>{batch.exceptionRecords}</b></span></div><i><em style={{ width: `${matchRate}%` }} /></i><p>{matchRate.toFixed(1)}% automatically matched</p>{batch.status === "signed_off" ? <div className="recon-signoff-complete"><b>✓ Independently signed off</b><span>{batch.reviewedBy ?? "Authorized reviewer"} · {batch.evidenceReference ?? "Evidence recorded"}</span></div> : batch.status !== "superseded" && openExceptions.length === 0 && batch.totalRecords > 0 && hasPermission(role, COMPLIANCE_PERMISSIONS.reconciliationSignoff) ? <div className="recon-signoff"><label>Evidence reference<input value={evidenceReference} onChange={(event) => setEvidenceReference(event.target.value)} maxLength={160} placeholder="Bank, CSD or custody reference" /></label><button className="btn primary small" disabled={Boolean(resolvingId) || evidenceReference.trim().length < 3} onClick={() => onSignOff(evidenceReference)}>{resolvingId === "signoff" ? "Signing off…" : "Sign off"}</button><small>The importer cannot sign off their own batch.</small></div> : null}{batch.status !== "superseded" && batch.source !== undefined && endOfDay.status !== "closed" && <div className="recon-reprocess"><label>Controlled reprocessing reason<input value={reprocessReason} maxLength={500} onChange={(event) => setReprocessReason(event.target.value)} placeholder="Internal book correction or late source confirmation" /></label><button className="btn secondary small" disabled={Boolean(resolvingId) || reprocessReason.trim().length < 10} onClick={() => onReprocess(reprocessReason)}>{resolvingId === "reprocess" ? "Reprocessing…" : "Reprocess retained file"}</button></div>}</section>
    </div>
    <section className="panel exception-panel"><div className="panel-head"><div><span className="eyebrow">OPEN EXCEPTIONS</span><h2>Items requiring resolution</h2></div><span className="exception-count">{openExceptions.length} open</span></div>{batch.status === "superseded" ? <EmptyState title="Batch superseded" copy="This immutable attempt remains available as evidence. Review the replacement batch for current results." /> : openExceptions.length ? openExceptions.map((exception) => {
      const expected = Number(exception.expectedValue ?? 0);
      const actual = Number(exception.actualValue ?? 0);
      const difference = Math.abs(expected - actual);
      return <div className="exception-row" key={exception.id}><span className={`queue-icon ${exception.exceptionType === "cash_variance" ? "danger" : "warning"}`}>!</span><div><b>{exception.exceptionType.replaceAll("_", " ")} · {exception.reference}</b><small>{exception.expectedValue === null ? "No internal trade matched this reference" : `Expected ${fmt.format(expected)} · File ${fmt.format(actual)}`}</small></div><strong>{exception.expectedValue === null ? "Unmatched" : exception.exceptionType === "cash_variance" ? `${etb(difference)}` : `${fmt.format(difference)} units`}</strong><button className="btn secondary small" disabled={resolvingId === exception.id} onClick={() => onResolve(exception.id)}>{resolvingId === exception.id ? "Resolving…" : "Resolve"}</button></div>;
    }) : <EmptyState title="Reconciliation is clear" copy="Every uploaded record matched the internal trade book." />}</section>
  </>;
}
